#!/bin/bash

if [ -z "$1" ]; then
	echo "ERROR: No TV show was provided."
	exit
fi

TEMPINDEX=$(lynx -dump -nolist epguides.com/$1 | grep "Episode #")
SEARCH="Titles"
let INDEX=${#TEMPINDEX}-6

# for seasons 1  to 9
for file in [0-9]-[0-9][0-9].*; do
	FILENAME="${file%.*}"
	EXT="${file##*.}"
	if [ ${#FILENAME} == 4 ]; then
		OOGA=$(lynx -width=300 -dump -nolist epguides.com/$1 | grep "$FILENAME")
		TITLE=${OOGA:$INDEX}
		TITLE=${TITLE//\ \[*\]/}
		TITLE=${TITLE//\ \([0-9]\)/}
		if [[ $TITLE == "" ]]; then
			let INDEX=${#TEMPINDEX}-13
			echo "inside"
		fi
		echo "$file   >>>   $FILENAME - $TITLE.$EXT"
		mv "$file" "$FILENAME - $TITLE.$EXT"
	fi
done

# for seasons 10+
for file in [0-9][0-9]-[0-9][0-9].*; do
	FILENAME="${file%.*}"
	EXT="${file##*.}"
	if [ ${#FILENAME} == 5 ]; then
		OOGA=$(lynx -width=300 -dump -nolist epguides.com/$1 | grep "$FILENAME")
		TITLE=${OOGA:$INDEX}
		TITLE=${TITLE//\ \[*\]/}
		echo "$file   >>>   $FILENAME - $TITLE.$EXT"
		mv "$file" "$FILENAME - $TITLE.$EXT"
	fi
done