#!/bin/bash

# match "#-##" to "#-## - "

# check if show title was provided
# if not, quit
if [ -z "$1" ]; then
	echo "ERROR: No TV show was provided."
	exit
fi

# grab the source txt
TEMPINDEX=$(lynx -dump -nolist epguides.com/$1 | grep "Episode #")
SEARCH="Titles"
let INDEX=${#TEMPINDEX}-6

# need to work on epguides.com search for
#	1-01 OR 1- 1
#	"Episode Title" OR "Titles"
# need to support double episode files, such as s01e02-03

# For seasons 1  to 9
for file in [0-9]-[0-9][0-9].*; do
	FILENAME="${file%.*}"
	EXT="${file##*.}"
	if [ ${#FILENAME} == 4 ]; then
		OOGA=$(lynx -width=300 -dump -nolist epguides.com/$1 | grep "$FILENAME")
		TITLE=${OOGA:$INDEX}
		TITLE=${TITLE//\ \[*\]/}
		TITLE=${TITLE//\ \([0-9]\)/}
		if [[ $TITLE == "" ]]; then
			let INDEX=${#TEMPINDEX}-13
			echo "inside"
		fi
		echo "$file   >>>   $FILENAME - $TITLE.$EXT"
		mv "$file" "$FILENAME - $TITLE.$EXT"
	fi
done

# For seasons 10+
for file in [0-9][0-9]-[0-9][0-9].*; do
	FILENAME="${file%.*}"
	EXT="${file##*.}"
	if [ ${#FILENAME} == 5 ]; then
		OOGA=$(lynx -width=300 -dump -nolist epguides.com/$1 | grep "$FILENAME")
		TITLE=${OOGA:$INDEX}
		TITLE=${TITLE//\ \[*\]/}
		echo "$file   >>>   $FILENAME - $TITLE.$EXT"
		mv "$file" "$FILENAME - $TITLE.$EXT"
	fi
done